    <div id="mainContent" class="tastingroom">
    <a href='http://localhost/cgv'><div style="cursor: hand; width: 100%; height: 60px; margin-bottom: -60px;" ></div></a>
    <!-- title -->
        <div id="pagebody">
        <div id="pagetitle">
        <img src="http://www.cgv.com/images/title_tasting_room.gif" alt="tastingroom" />
        </div>
    
                    <h1>Hours, Directions and Tasting Programs</h1>
                <p><p><span style="font-size: medium;"><strong><span style="font-family: Times New Roman;">Wine Tasting</span></strong></span><span style="font-size: large;"><strong><span style="font-family: Times New Roman;"> </span></strong><span style="font-family: Times New Roman;"><img directions="" width="501" height="334" align="right" alt="" src="/coopergarrod/up/editor/image/Tasting%20room%20afternoon.jpg" /></span> &nbsp;</span></p>
<p><span style="font-size: medium;"><span style="font-family: &quot;Times New Roman&quot;;">Our historic tasting room, the Fruit House, is open daily (weekdays, 12-5;&nbsp;weekends, 11-5), except for these special Holiday hours: open 12-3 Christmas Eve &amp; New Year's Eve;  closed Easter, Thanksgiving, Christmas Day, and New Year's Day.</span></span></p>
<p><span style="font-size: medium;"><span style="font-family: &quot;Times New Roman&quot;;">There is a tasting fee of $15 for five wines, which change on a weekly basis.</span></span></p>
<p><span style="font-size: medium;"><span style="font-family: &quot;Times New Roman&quot;;">Artisan cheeses, charcuterie, olives, crackers, and bottled water are available for purchase here in the Tasting Room! You may also bring a </span></span><span style="font-size: medium;"><span style="font-family: &quot;Times New Roman&quot;;"><a href="/dyn/picnics">picnic</a>,&nbsp;</span></span><span style="font-family: &quot;Times New Roman&quot;; font-size: medium;">or&nbsp;plan on lunch or dinner in one of Saratoga's great restaurants.</span></p>
<p><span style="font-size: medium;"><span style="font-family: &quot;Times New Roman&quot;;"><strong><span style="font-family: Times New Roman;">Group Tasting (8 or More)</span></strong></span></span></p>
<p><span style="font-size: medium;"><span style="font-family: Times New Roman;">Reservations are requested for those groups of 8 or more interested in wine tasting during our regular tasting room hours.&nbsp; Please email <a href="javascript:location.href='mailto:'+String.fromCharCode(101,118,101,110,116,115,64,99,103,118,46,99,111,109)+'?subject=Group%20Tasting%20Reservation'">events@cgv.com</a> or call 408-867-7116 to make your reservation.&nbsp; Group tastings of 16 or more will be asked to pay in advance.</span></span></p>
<p><span style="font-size: medium;"><strong><span style="font-family: &quot;Times New Roman&quot;;">Private Tastings</span></strong></span></p>
<p><span style="font-family: &quot;Times New Roman&quot;;"><span style="font-size: medium;">We are happy to welcome your group for a private wine tasting for $25/person plus tax, 10 person minimum.&nbsp; Private tastings are great for small groups that might enjoy a more intimate tasting experience with a personal tasting room host; or for larger groups that simply require more attention to ensure everyone has a good time.&nbsp; To inquire about a private tasting, please email <a href="javascript:location.href='mailto:'+String.fromCharCode(101,118,101,110,116,115,64,99,103,118,46,99,111,109)+'?subject=Private%20Tasting%20inquiry'">events@cgv.com</a> or call 408-867-7116.</span></span><span style="font-family: &quot;Times New Roman&quot;;"><span style="font-size: medium;">&nbsp;</span></span></p>
<p><strong><span style="font-family: &quot;Times New Roman&quot;;"><span style="font-size: medium;">Team Building and Tasting<br />
</span></span></strong></p>
<p><span style="font-family: &quot;Times New Roman&quot;;"><span style="font-size: medium;">We offer a number of <a href="http://www.cgv.com/dyn/getaway">team building activities</a> for your company off-site event or personal party!&nbsp; From blind wine tasting challenges to chocolate pairing and wine blending workshops, we can accommodate groups of a variety of sizes.&nbsp; Email <a href="javascript:location.href='mailto:'+String.fromCharCode(101,118,101,110,116,115,64,99,103,118,46,99,111,109)+'?subject=Team%20Building%20inquiry'">events@cgv.com</a> or call 408-867-7116 to inquire.</span></span></p>
<h3><span style="font-size: medium;"><span style="font-family: Times New Roman;"><strong>How to find us</strong></span></span><span style="font-family: &quot;Times New Roman&quot;;">: </span><a href="dyn/directions"><span style="font-family: &quot;Times New Roman&quot;;">(click here for map)</span></a></h3>
<p style="margin-left: 40px;"><span style="font-family: &quot;Times New Roman&quot;;"><em><strong>From Highway 280</strong></em><strong> </strong>- take Foothill Expwy exit; south towards the hills for 5 miles on Foothill Blvd which becomes Stevens Canyon Rd when it crosses Stevens Creek Blvd and continues past Stevens Creek Reservoir and into Stevens Canyon; left fork at stop sign in Stevens Canyon onto Mt Eden Rd for 1.6 miles, left on Garrod Rd. About 15 minutes.</span></p>
<p style="margin-left: 40px;"><span style="font-family: &quot;Times New Roman&quot;;"><em><strong>From Highway 85</strong></em> - take De Anza Blvd exit; west towards Saratoga for 1 mile; right on Pierce Rd for 1.8 miles; right on Mt Eden Rd for 1 mile; right on Garrod Rd. About 10 minutes</span></p>
<p style="text-align: center;"><a href="http://maps.google.com/maps?q=22645%2Bgarrod%2Broad,%2Bsaratoga,%2Bca%2B95070&amp;hl=en"><span style="font-family: &quot;Times New Roman&quot;;">Google</span></a><span style="font-family: &quot;Times New Roman&quot;;">, </span><a href="http://www.mapquest.com/maps/map.adp?city=saratoga&amp;state=CA&amp;address=22645%2Bgarrod%2Brd&amp;zip=95070&amp;country=us&amp;zoom=5#a/maps/l::22645+Garrod+Rd:Saratoga:CA:95070-9781:US:37.275794:-122.058293:address:Santa+Clara+County:1/m:hyb:12:37.275794:-122.058293:0:::::/io:0:::::f:EN:M:/e"><span style="font-family: &quot;Times New Roman&quot;;">Mapquest</span></a><span style="font-family: &quot;Times New Roman&quot;;">, and </span><a href="http://maps.yahoo.com/maps_result?addr=22645%20garrod%20road&amp;csz=95070&amp;country=us&amp;new=1&amp;name=&amp;qty="><span style="font-family: &quot;Times New Roman&quot;;">Yahoo</span></a><span style="font-family: &quot;Times New Roman&quot;;"> maps</span></p>
<p style="text-align: center;"><span style="font-family: &quot;Times New Roman&quot;;"><strong>Driving times:</strong> both ways only 10-15 minutes.</span><span style="font-family: Times New Roman;"><br />
</span></p>
<p style="text-align: center;"><span style="font-family: Times New Roman;"><br />
</span></p>
<p>&nbsp;</p></p>
        <div class="clear" />
        </div>
    <!-- end #mainContent --></div>
<!-- end #container --></div>