    <div id="mainContent" class="tastingroom">
    <a href='http://localhost/cgv'><div style="cursor: hand; width: 100%; height: 60px; margin-bottom: -60px;" ></div></a>
    <!-- title -->
        <div id="pagebody">
        <div id="pagetitle">
        <img src="http://www.cgv.com/images/title_tasting_room.gif" alt="tastingroom" />
        </div>
    
                    <h1>Tours</h1>
                <p><p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><span style="font-family: 'Times New Roman';"><span style="font-size: medium;">In addition to daily wine tasting, we offer several different tours:</span></span></p>
<ul style="font-family: 'Times New Roman', Times, serif; font-size: 16px;">
    <li><a href="http://www.cgv.com/tours#firstsat" style="color: rgb(3, 8, 115);"><span style="color: rgb(0, 0, 255);"><span style="font-family: 'Times New Roman';"><span style="font-size: medium;">Walk with the Winemaker</span></span></span></a></li>
    <li><a href="http://www.cgv.com/tours#eco" style="color: rgb(3, 8, 115);"><span style="color: rgb(0, 0, 255);"><span style="font-family: 'Times New Roman';"><span style="font-size: medium;">Eco-tours</span></span></span></a></li>
    <li><a href="http://www.cgv.com/tours#special" style="color: rgb(3, 8, 115);"><span style="color: rgb(0, 0, 255);"><span style="font-family: 'Times New Roman';"><span style="font-size: medium;">Groups</span></span></span></a></li>
    <li><span style="color: rgb(0, 0, 255);"><a href="http://www.cgv.com/tours#bottling" style="color: rgb(3, 8, 115);"><span style="font-family: 'Times New Roman';"><span style="font-size: medium;">Bottling</span></span></a></span><span style="font-size: medium;"><br />
    </span></li>
</ul>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><a id="firstsat" name="firstsat"></a><span style="font-family: 'Times New Roman';"><strong><span style="font-size: medium;">Walk with the Winemaker</span></strong></span></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">On the first Saturday of the month, at 11 AM, we offer an in-depth, winemaker-guided tour of our vineyards and winery followed by a&nbsp;tasting of&nbsp;our wines.&nbsp; Walk through our Chardonnay vineyard, see our tank farm and visit our barrel room while learning about our family history as well as our farming and winemaking practices here at Cooper-Garrod.</span></span></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">Consider bringing a picnic lunch to enjoy!&nbsp; Leave it in a cooler in your car for the tour; and when you return to the tasting room following the walk, taste some wines and choose the perfect bottle of Cooper-Garrod wine to enjoy with your meal.</span></span></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">We meet on the steps of the Tasting Room.&nbsp; The tour is free; tasting is $15/person.&nbsp; Please limit your group to 8.&nbsp; If you have more, please consider a Private Group Tour.&nbsp; Email&nbsp;<a style="color: rgb(3, 8, 115);">events@cgv.com</a>&nbsp;or call 408-867-7116 to reserve your spot.<br />
</span></span></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><a id="eco" name="eco"></a><strong><span style="font-family: 'Times New Roman';"><span style="font-size: medium;">Eco-Tours</span></span></strong></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><img width="300" hspace="5" height="225" border="0" align="left" alt="" src="http://www.cgv.com/coopergarrod/up/editor/image/EcoDocent-300.jpg" /><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">Join our docent, local eco-expert Ramblin' Bill&nbsp;Bosworth, on a casual and up-close hike through Cooper-Garrod Estate Vineyards, Garrod Farms, and the adjoining Fremont Older Open Space Preserve. This is a great opportunity to see spectacular scenery while learning about local flora and fauna as well as touching on our organic and sustainable winegrowing practices.</span></span></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">This moderate hike starts at our Tasting Room at 10 am and lasts approximately an hour and a half</span></span>.&nbsp;&nbsp;<span style="font-size: medium;"><span style="font-family: 'Times New Roman';">Wear comfortable footwear appropriate for dirt trails and hills.&nbsp; Bring sunscreen and perhaps a hat and water bottle, especially on hot days.&nbsp;&nbsp;</span></span><span style="font-size: medium;"><span style="font-family: 'Times New Roman';"><br />
</span></span></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">Consider bringing a picnic lunch to enjoy post-hike!&nbsp; Leave it a cooler in your car during the hike; after you return to the Tasting Room, do some wine tasting to choose the perfect bottle of Cooper-Garrod wine to accompany your picnic.&nbsp; It's a lovely way to spend an afternoon.<br />
</span></span></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">No charge for the tour!&nbsp; If you plan to come, please email us at&nbsp;<a style="color: rgb(3, 8, 115);">events@cgv.com</a>&nbsp;or call 408-867-7116 to reserve your spot.</span></span></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><a id="special" name="special"></a><span style="font-family: 'Times New Roman';"><strong><span style="font-size: medium;">Private Group Tours</span></strong></span></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">Our in-depth, winemaker-guided tour is available by special arrangement for 8 or more people for $20 per person plus tax. Tours are subject to availability and</span></span><span style="color: rgb(0, 0, 255);"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">&nbsp;</span></span></span><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">should be requested at least 3 business days in advance - though the more advance notice, the better!&nbsp; Email&nbsp;<a href="javascript:location.href='mailto:'+String.fromCharCode(101,118,101,110,116,115,64,99,103,118,46,99,111,109)+'?subject=Private%20Tour%20Request'">events@cgv.com</a>&nbsp;to inquire.<br />
</span></span></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">Please include in your email the following information:&nbsp; the date you hope to visit, the time you hope to meet, a description of your group, and number of people expected.&nbsp;&nbsp;</span></span></p>
<h3 style="font-family: 'Times New Roman', Times, serif;"><a id="bottling" name="bottling"></a><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">Bottling Tour - July<br />
</span></span></h3>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">We use a mobile bottling line that is here for two days. With this tour, you can learn about the bottling process.&nbsp; We conduct 15-20 minute tours at 11 AM and 2 PM each day and conclude in the tasting room.</span></span></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">Typically we bottle in mid-July; the exact dates vary year to year.&nbsp; Check our events calendar in June for this year's bottling tour dates.</span></span></p>
<p style="font-family: 'Times New Roman', Times, serif; font-size: 16px;"><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">No charge for the tour, but&nbsp;</span></span><span style="font-size: medium;"><span style="font-family: 'Times New Roman';">reservations are required as space is limited. Please advise your 1st and 2nd choice (if any) for a tour time. This is up-close observation; please note you're not actually working the bottling line!&nbsp; Email <a href="javascript:location.href='mailto:'+String.fromCharCode(101,118,101,110,116,115,64,99,103,118,46,99,111,109)+'?subject=Bottling%20Tour%20Request'">events@cgv.com</a>&nbsp;with inquiries.</span></span></p></p>
        <div class="clear" />
        </div>
    <!-- end #mainContent --></div>
<!-- end #container --></div>