    <div id="mainContent" class="events">
    <a href='http://www.cgv.com/'><div style="cursor: hand; width: 100%; height: 60px; margin-bottom: -60px;" ></div></a>
    <!-- title -->
        <div id="pagebody">
        <div id="pagetitle">
        <img src="http://www.cgv.com/images/title_events.gif" alt="events" />
        </div>
    
                    <h1>Special Events, Activities and Picnics</h1>
                <p><p><img class="floater" alt="" src="images/photos/carosel-horse.jpg" /></p>
<p id="docs-internal-guid-64f6b584-888e-167e-2b42-fff6cbf5426e" style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; font-weight: 700; vertical-align: baseline;">Our Event Site</span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; vertical-align: baseline;">We offer a rustic outdoor environment for those seeking an event site.&nbsp; Most events take place alongside our winery in the picnic and plaza areas, underneath 100-year-old oak and eucalyptus trees.&nbsp; We do have a covered space in case of inclement weather.</span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; vertical-align: baseline;">We do not make or sell food, but we are happy to suggest a number of </span><a style="text-decoration: none;" href="http://www.cgv.com/dyn/caterers"><span style="color: rgb(0, 0, 255); font-size: 18px; text-decoration: underline; vertical-align: baseline;">catering options</span></a><span style="font-size: 18px; vertical-align: baseline;"> for your events.</span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; font-weight: 700; vertical-align: baseline;">Special Events</span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; vertical-align: baseline;">We are ideal for casual receptions, rehearsal dinners, or other special events!&nbsp; </span><a style="text-decoration: none;" href="http://www.cgv.com/dyn/someevents"><span style="color: rgb(0, 0, 255); font-size: 18px; text-decoration: underline; vertical-align: baseline;">Here</span></a><span style="font-size: 18px; vertical-align: baseline;"> are photos of some recent events.&nbsp; </span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; vertical-align: baseline;">Please note: because we are a working horse ranch as well as a winery and vineyard, we do not promote ourselves as a wedding venue.</span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; vertical-align: baseline;">To inquire about our event space, please email </span><span style="text-decoration: underline; color: rgb(0, 0, 255); font-size: 18px; vertical-align: baseline;"><a href="javascript:location.href='mailto:'+String.fromCharCode(101,118,101,110,116,115,64,99,103,118,46,99,111,109)+'?subject=Event%20Request'">events@cgv.com</a></span><span style="font-size: 18px; vertical-align: baseline;">.</span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; font-weight: 700; vertical-align: baseline;">Activities - Group or Corporate</span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; vertical-align: baseline;">We offer a number of activities for groups looking to learn or experience more about wine as well as for businesses looking for <a href="http://www.cgv.com/dyn/getaway">team building activities</a>.&nbsp;&nbsp; </span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; vertical-align: baseline;">These activities include: a blind wine tasting challenge, a wine and chocolate pairing workshop, a component tasting and blending workshop, and of course, our wine ride - a one-hour guided horseback ride combined with wine tasting.</span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; vertical-align: baseline;">If you would like to arrange an activity for your group, please email <u><a href="javascript:location.href='mailto:'+String.fromCharCode(101,118,101,110,116,115,64,99,103,118,46,99,111,109)+'?subject=Team%20Building%20Request'">events@cgv.com</a></u></span><span style="font-size: 18px; vertical-align: baseline;">.</span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; font-weight: 700; vertical-align: baseline;">Picnics</span><span style="font-size: 18px; vertical-align: baseline;"> </span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; vertical-align: baseline;">We are a great place to enjoy some wine while taking in a picnic!&nbsp; For groups of 8 or less - which is essentially enough people for one picnic table - our picnic area requires no reservation.&nbsp; Come into the tasting room first to select your wines, and then head to a picnic table to enjoy the afternoon!&nbsp; </span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; vertical-align: baseline;">For those groups of 8 or more planning to picnic, we do ask that you make a reservation</span><span style="font-size: 18px; vertical-align: baseline;">&nbsp;ahead of time by emailing; <a href="javascript:location.href='mailto:'+String.fromCharCode(101,118,101,110,116,115,64,99,103,118,46,99,111,109)+'?subject=Picnic%20Table%20Request'">events@cgv.com</a>&nbsp;</span><span style="font-size: 18px;">or by calling 408-867-7116.&nbsp; One group per reservation, please.</span></p>
<p style="line-height: 1.2; margin-top: 5pt; margin-bottom: 5pt;" dir="ltr"><span style="font-size: 18px; vertical-align: baseline;">To ensure a good time to be had by all, we do ask that all those using our picnic area respect our </span><a style="text-decoration: none;" href="http://www.cgv.com/dyn/picnics"><span style="color: rgb(0, 0, 255); font-size: 18px; text-decoration: underline; vertical-align: baseline;">picnic area policies</span></a><span style="font-size: 18px; vertical-align: baseline;">.&nbsp;&nbsp;</span></p>
<p><br />
&nbsp;</p></p>
        <div class="clear" />
        </div>
    <!-- end #mainContent --></div>
    <div id="legal">Copyright &copy; 2019 Cooper Garrod Vineyards &nbsp; <a style='color: white;' href='dyn/termsandconditions'>Terms and Conditions</a><br />
	<a href="http://damionhickman.com" target="_blank"><img src="images/slug.gif" alt="Site by Damion Hickman Design" border="0" /></a></div>
<!-- end #container --></div>